project:
  type: website
  output-dir: docs
  preview: 
    port: 4200


website:
  title: "KMO"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      

format:
  html:
    theme: 
      light: lux
      dark: quartz
    css: styles.css
    toc: true



