project:
  type: website
  output-dir: docs
  preview: 
    port: 4200

execute:
  freeze: true 

website:
  title: "KMO"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - projects.qmd
      - resume.qmd
      - hobbies.qmd
      - about.qmd
  announcement: 
    content: "⚠️ **New** - this website is under construction 🚧 as of July 2024." 
    position: below-navbar       

format:
  html:
    theme: 
      light: lux
      dark: quartz
    css: styles.css
    toc: true


